namespace DataRepository.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class allrequiredfields : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.WorkerPersonAssignments", "Administration_Id", "dbo.Administrations");
            DropForeignKey("dbo.Users", "Role_Id", "dbo.Roles");
            DropForeignKey("dbo.Offers", "CreatedBy_Id", "dbo.Providers");
            DropForeignKey("dbo.Offers", "Customer_Id", "dbo.Customers");
            DropForeignKey("dbo.Offers", "Product_Id", "dbo.Products");
            DropForeignKey("dbo.Vendors", "Address_Id", "dbo.Addresses");
            DropForeignKey("dbo.Vendors", "Contact_Id", "dbo.Users");
            DropForeignKey("dbo.Products", "Category_Id", "dbo.Categories");
            DropForeignKey("dbo.PersonRequests", "Category_Id", "dbo.Categories");
            DropForeignKey("dbo.PersonRequests", "Customer_Id", "dbo.Customers");
            DropForeignKey("dbo.ReturnRequests", "CreatedBy_Id", "dbo.Users");
            DropForeignKey("dbo.WorkerPersonAssignments", "ApprovedBy_Id", "dbo.Workers");
            DropForeignKey("dbo.Workers", "User_Id", "dbo.Users");
            DropIndex("dbo.Users", new[] { "Role_Id" });
            DropIndex("dbo.Offers", new[] { "CreatedBy_Id" });
            DropIndex("dbo.Offers", new[] { "Customer_Id" });
            DropIndex("dbo.Offers", new[] { "Product_Id" });
            DropIndex("dbo.Providers", new[] { "UserId_Id" });
            DropIndex("dbo.Vendors", new[] { "Address_Id" });
            DropIndex("dbo.Vendors", new[] { "Contact_Id" });
            DropIndex("dbo.Products", new[] { "Category_Id" });
            DropIndex("dbo.Products", new[] { "CreatedBy_Id" });
            DropIndex("dbo.PersonRequests", new[] { "Category_Id" });
            DropIndex("dbo.PersonRequests", new[] { "Customer_Id" });
            DropIndex("dbo.ReturnRequests", new[] { "CreatedBy_Id" });
            DropIndex("dbo.ReturnRequests", new[] { "Offer_Id" });
            DropIndex("dbo.WorkerPersonAssignments", new[] { "Administration_Id" });
            DropIndex("dbo.WorkerPersonAssignments", new[] { "ApprovedBy_Id" });
            DropIndex("dbo.Workers", new[] { "User_Id" });
            RenameColumn(table: "dbo.Providers", name: "UserId_Id", newName: "User_Id");
            AddColumn("dbo.WorkerPersonAssignments", "AssignmentStatusId", c => c.Int(nullable: false));
            AlterColumn("dbo.Users", "Email", c => c.String(nullable: false));
            AlterColumn("dbo.Users", "Password", c => c.String(nullable: false));
            AlterColumn("dbo.Users", "Phone", c => c.String(nullable: false));
            AlterColumn("dbo.Users", "Role_Id", c => c.Int(nullable: false));
            AlterColumn("dbo.Roles", "Name", c => c.String(nullable: false));
            AlterColumn("dbo.Offers", "CreatedBy_Id", c => c.Int(nullable: false));
            AlterColumn("dbo.Offers", "Customer_Id", c => c.Int(nullable: false));
            AlterColumn("dbo.Offers", "Product_Id", c => c.Int(nullable: false));
            AlterColumn("dbo.Providers", "User_Id", c => c.Int(nullable: false));
            AlterColumn("dbo.Vendors", "Name", c => c.String(nullable: false));
            AlterColumn("dbo.Vendors", "Description", c => c.String(nullable: false));
            AlterColumn("dbo.Vendors", "Email", c => c.String(nullable: false));
            AlterColumn("dbo.Vendors", "Address_Id", c => c.Int(nullable: false));
            AlterColumn("dbo.Vendors", "Contact_Id", c => c.Int(nullable: false));
            AlterColumn("dbo.Products", "Name", c => c.String(nullable: false));
            AlterColumn("dbo.Products", "IsNew", c => c.Boolean(nullable: false));
            AlterColumn("dbo.Products", "Category_Id", c => c.Int(nullable: false));
            AlterColumn("dbo.Products", "CreatedBy_Id", c => c.Int(nullable: false));
            AlterColumn("dbo.Permissions", "Name", c => c.String(nullable: false));
            AlterColumn("dbo.PersonRequests", "Description", c => c.String(nullable: false));
            AlterColumn("dbo.PersonRequests", "Category_Id", c => c.Int(nullable: false));
            AlterColumn("dbo.PersonRequests", "Customer_Id", c => c.Int(nullable: false));
            AlterColumn("dbo.ReturnRequests", "Reason", c => c.String(nullable: false));
            AlterColumn("dbo.ReturnRequests", "CreatedBy_Id", c => c.Int(nullable: false));
            AlterColumn("dbo.ReturnRequests", "Offer_Id", c => c.Int(nullable: false));
            AlterColumn("dbo.WorkerPersonAssignments", "ApprovedBy_Id", c => c.Int(nullable: false));
            AlterColumn("dbo.Workers", "User_Id", c => c.Int(nullable: false));
            CreateIndex("dbo.Users", "Role_Id");
            CreateIndex("dbo.Offers", "CreatedBy_Id");
            CreateIndex("dbo.Offers", "Customer_Id");
            CreateIndex("dbo.Offers", "Product_Id");
            CreateIndex("dbo.Providers", "User_Id");
            CreateIndex("dbo.Vendors", "Address_Id");
            CreateIndex("dbo.Vendors", "Contact_Id");
            CreateIndex("dbo.Products", "Category_Id");
            CreateIndex("dbo.Products", "CreatedBy_Id");
            CreateIndex("dbo.PersonRequests", "Category_Id");
            CreateIndex("dbo.PersonRequests", "Customer_Id");
            CreateIndex("dbo.ReturnRequests", "CreatedBy_Id");
            CreateIndex("dbo.ReturnRequests", "Offer_Id");
            CreateIndex("dbo.WorkerPersonAssignments", "ApprovedBy_Id");
            CreateIndex("dbo.Workers", "User_Id");
            AddForeignKey("dbo.Users", "Role_Id", "dbo.Roles", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Offers", "CreatedBy_Id", "dbo.Providers", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Offers", "Customer_Id", "dbo.Customers", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Offers", "Product_Id", "dbo.Products", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Vendors", "Address_Id", "dbo.Addresses", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Vendors", "Contact_Id", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Products", "Category_Id", "dbo.Categories", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PersonRequests", "Category_Id", "dbo.Categories", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PersonRequests", "Customer_Id", "dbo.Customers", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ReturnRequests", "CreatedBy_Id", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.WorkerPersonAssignments", "ApprovedBy_Id", "dbo.Workers", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Workers", "User_Id", "dbo.Users", "Id", cascadeDelete: true);
            DropColumn("dbo.ProductSchedules", "AvailableOnThursday");
            DropColumn("dbo.WorkerPersonAssignments", "StatusId");
            DropColumn("dbo.WorkerPersonAssignments", "Administration_Id");
        }
        
        public override void Down()
        {
            AddColumn("dbo.WorkerPersonAssignments", "Administration_Id", c => c.Int());
            AddColumn("dbo.WorkerPersonAssignments", "StatusId", c => c.Int(nullable: false));
            AddColumn("dbo.ProductSchedules", "AvailableOnThursday", c => c.Boolean(nullable: false));
            DropForeignKey("dbo.Workers", "User_Id", "dbo.Users");
            DropForeignKey("dbo.WorkerPersonAssignments", "ApprovedBy_Id", "dbo.Workers");
            DropForeignKey("dbo.ReturnRequests", "CreatedBy_Id", "dbo.Users");
            DropForeignKey("dbo.PersonRequests", "Customer_Id", "dbo.Customers");
            DropForeignKey("dbo.PersonRequests", "Category_Id", "dbo.Categories");
            DropForeignKey("dbo.Products", "Category_Id", "dbo.Categories");
            DropForeignKey("dbo.Vendors", "Contact_Id", "dbo.Users");
            DropForeignKey("dbo.Vendors", "Address_Id", "dbo.Addresses");
            DropForeignKey("dbo.Offers", "Product_Id", "dbo.Products");
            DropForeignKey("dbo.Offers", "Customer_Id", "dbo.Customers");
            DropForeignKey("dbo.Offers", "CreatedBy_Id", "dbo.Providers");
            DropForeignKey("dbo.Users", "Role_Id", "dbo.Roles");
            DropIndex("dbo.Workers", new[] { "User_Id" });
            DropIndex("dbo.WorkerPersonAssignments", new[] { "ApprovedBy_Id" });
            DropIndex("dbo.ReturnRequests", new[] { "Offer_Id" });
            DropIndex("dbo.ReturnRequests", new[] { "CreatedBy_Id" });
            DropIndex("dbo.PersonRequests", new[] { "Customer_Id" });
            DropIndex("dbo.PersonRequests", new[] { "Category_Id" });
            DropIndex("dbo.Products", new[] { "CreatedBy_Id" });
            DropIndex("dbo.Products", new[] { "Category_Id" });
            DropIndex("dbo.Vendors", new[] { "Contact_Id" });
            DropIndex("dbo.Vendors", new[] { "Address_Id" });
            DropIndex("dbo.Providers", new[] { "User_Id" });
            DropIndex("dbo.Offers", new[] { "Product_Id" });
            DropIndex("dbo.Offers", new[] { "Customer_Id" });
            DropIndex("dbo.Offers", new[] { "CreatedBy_Id" });
            DropIndex("dbo.Users", new[] { "Role_Id" });
            AlterColumn("dbo.Workers", "User_Id", c => c.Int());
            AlterColumn("dbo.WorkerPersonAssignments", "ApprovedBy_Id", c => c.Int());
            AlterColumn("dbo.ReturnRequests", "Offer_Id", c => c.Int());
            AlterColumn("dbo.ReturnRequests", "CreatedBy_Id", c => c.Int());
            AlterColumn("dbo.ReturnRequests", "Reason", c => c.String());
            AlterColumn("dbo.PersonRequests", "Customer_Id", c => c.Int());
            AlterColumn("dbo.PersonRequests", "Category_Id", c => c.Int());
            AlterColumn("dbo.PersonRequests", "Description", c => c.String());
            AlterColumn("dbo.Permissions", "Name", c => c.String());
            AlterColumn("dbo.Products", "CreatedBy_Id", c => c.Int());
            AlterColumn("dbo.Products", "Category_Id", c => c.Int());
            AlterColumn("dbo.Products", "IsNew", c => c.Boolean());
            AlterColumn("dbo.Products", "Name", c => c.String());
            AlterColumn("dbo.Vendors", "Contact_Id", c => c.Int());
            AlterColumn("dbo.Vendors", "Address_Id", c => c.Int());
            AlterColumn("dbo.Vendors", "Email", c => c.String());
            AlterColumn("dbo.Vendors", "Description", c => c.String());
            AlterColumn("dbo.Vendors", "Name", c => c.String());
            AlterColumn("dbo.Providers", "User_Id", c => c.Int());
            AlterColumn("dbo.Offers", "Product_Id", c => c.Int());
            AlterColumn("dbo.Offers", "Customer_Id", c => c.Int());
            AlterColumn("dbo.Offers", "CreatedBy_Id", c => c.Int());
            AlterColumn("dbo.Roles", "Name", c => c.String());
            AlterColumn("dbo.Users", "Role_Id", c => c.Int());
            AlterColumn("dbo.Users", "Phone", c => c.String());
            AlterColumn("dbo.Users", "Password", c => c.String());
            AlterColumn("dbo.Users", "Email", c => c.String());
            DropColumn("dbo.WorkerPersonAssignments", "AssignmentStatusId");
            RenameColumn(table: "dbo.Providers", name: "User_Id", newName: "UserId_Id");
            CreateIndex("dbo.Workers", "User_Id");
            CreateIndex("dbo.WorkerPersonAssignments", "ApprovedBy_Id");
            CreateIndex("dbo.WorkerPersonAssignments", "Administration_Id");
            CreateIndex("dbo.ReturnRequests", "Offer_Id");
            CreateIndex("dbo.ReturnRequests", "CreatedBy_Id");
            CreateIndex("dbo.PersonRequests", "Customer_Id");
            CreateIndex("dbo.PersonRequests", "Category_Id");
            CreateIndex("dbo.Products", "CreatedBy_Id");
            CreateIndex("dbo.Products", "Category_Id");
            CreateIndex("dbo.Vendors", "Contact_Id");
            CreateIndex("dbo.Vendors", "Address_Id");
            CreateIndex("dbo.Providers", "UserId_Id");
            CreateIndex("dbo.Offers", "Product_Id");
            CreateIndex("dbo.Offers", "Customer_Id");
            CreateIndex("dbo.Offers", "CreatedBy_Id");
            CreateIndex("dbo.Users", "Role_Id");
            AddForeignKey("dbo.Workers", "User_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.WorkerPersonAssignments", "ApprovedBy_Id", "dbo.Workers", "Id");
            AddForeignKey("dbo.ReturnRequests", "CreatedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.PersonRequests", "Customer_Id", "dbo.Customers", "Id");
            AddForeignKey("dbo.PersonRequests", "Category_Id", "dbo.Categories", "Id");
            AddForeignKey("dbo.Products", "Category_Id", "dbo.Categories", "Id");
            AddForeignKey("dbo.Vendors", "Contact_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.Vendors", "Address_Id", "dbo.Addresses", "Id");
            AddForeignKey("dbo.Offers", "Product_Id", "dbo.Products", "Id");
            AddForeignKey("dbo.Offers", "Customer_Id", "dbo.Customers", "Id");
            AddForeignKey("dbo.Offers", "CreatedBy_Id", "dbo.Providers", "Id");
            AddForeignKey("dbo.Users", "Role_Id", "dbo.Roles", "Id");
            AddForeignKey("dbo.WorkerPersonAssignments", "Administration_Id", "dbo.Administrations", "Id");
        }
    }
}
