// <auto-generated />
namespace DataRepository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Updated_CareRequest_table_added_status : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updated_CareRequest_table_added_status));
        
        string IMigrationMetadata.Id
        {
            get { return "201905051514350_Updated_CareRequest_table_added_status"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
