// <auto-generated />
namespace DataRepository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_columns_to_assignmnets : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_columns_to_assignmnets));
        
        string IMigrationMetadata.Id
        {
            get { return "201906011706051_added_columns_to_assignmnets"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
